import pandas as pd
import streamlit as st

from core.evidence_engine import get_biomarker_evidence


def _fmt(value, digits=3):
    if value is None:
        return "N/A"

    try:
        return f"{float(value):.{digits}f}"
    except (TypeError, ValueError):
        return str(value)


def show_biomarker_explorer(data):

    st.title("🧬 Biomarker Explorer")

    st.markdown(
        """
        Explore individual LUAD biomarker candidates across the
        evidence generated by the validated V1 biomarker pipeline.
        """
    )

    st.divider()

    # ==========================================================
    # DATA
    # ==========================================================

    top15 = data.get("top15")

    if top15 is None or top15.empty:
        st.warning("Top biomarker data could not be loaded.")
        return

    if "gene_name" not in top15.columns:
        st.error("The top biomarker dataset does not contain gene_name.")
        return

    genes = (
        top15["gene_name"]
        .dropna()
        .astype(str)
        .unique()
        .tolist()
    )

    if not genes:
        st.warning("No biomarker genes are available.")
        return

    # ==========================================================
    # GENE SELECTION
    # ==========================================================

    selected_gene = st.selectbox(
        "🔎 Select a biomarker",
        genes,
        key="biomarker_explorer_gene_v2",
    )

    # ==========================================================
    # EVIDENCE ENGINE
    # ==========================================================

    evidence = get_biomarker_evidence(
        data,
        selected_gene,
    )

    if not evidence:
        st.error(
            f"No evidence could be retrieved for {selected_gene}."
        )
        return

    integrated = evidence.get(
        "integrated_ranking",
        {},
    )

    top = evidence.get(
        "top15",
        {},
    )

    roc = evidence.get(
        "roc_validation",
        {},
    )

    validation = evidence.get(
        "independent_validation",
        {},
    )

    ml = evidence.get(
        "machine_learning",
        {},
    )

    stability = evidence.get(
        "stability",
        {},
    )

    de = evidence.get(
        "differential_expression",
        {},
    )

    # ==========================================================
    # HEADER
    # ==========================================================

    st.header(f"🔬 {selected_gene}")

    st.caption(
        "Evidence retrieved from canonical V1-derived datasets."
    )

    # ==========================================================
    # KEY METRICS
    # ==========================================================

    col1, col2, col3, col4 = st.columns(4)

    with col1:
        rank = integrated.get("integrated_rank")

        st.metric(
            "🏆 Integrated Rank",
            f"#{int(rank)}"
            if rank is not None
            else "N/A",
        )

    with col2:
        auc = roc.get("AUC")

        st.metric(
            "📈 ROC-AUC",
            _fmt(auc),
        )

    with col3:
        stability_score = stability.get(
            "stability_score"
        )

        st.metric(
            "🔬 Stability",
            _fmt(stability_score),
        )

    with col4:
        validation_rank = top.get(
            "validation_rank"
        )

        st.metric(
            "✅ Validation Rank",
            f"#{int(validation_rank)}"
            if validation_rank is not None
            else "N/A",
        )

    st.divider()

    # ==========================================================
    # EVIDENCE PROFILE
    # ==========================================================

    st.subheader("🧩 Evidence Profile")

    evidence_items = {
        "Integrated Ranking": integrated.get(
            "integrated_score"
        ),
        "ROC-AUC": roc.get("AUC"),
        "Sensitivity": roc.get(
            "sensitivity"
        ),
        "Specificity": roc.get(
            "specificity"
        ),
        "ML Evidence": integrated.get(
            "score_ML"
        ),
        "Stability": integrated.get(
            "score_stability"
        ),
        "DE Evidence": integrated.get(
            "score_DE"
        ),
    }

    profile_rows = []

    for label, value in evidence_items.items():

        if value is not None:

            try:
                numeric_value = float(value)

                profile_rows.append(
                    {
                        "Evidence": label,
                        "Score": numeric_value,
                    }
                )

            except (
                TypeError,
                ValueError,
            ):
                pass

    if profile_rows:

        profile_df = pd.DataFrame(
            profile_rows
        )

        st.dataframe(
            profile_df,
            use_container_width=True,
            hide_index=True,
        )

    else:

        st.info(
            "No numerical evidence profile is available."
        )

    st.divider()

    # ==========================================================
    # ROC / VALIDATION
    # ==========================================================

    st.subheader(
        "📈 ROC / Independent Validation"
    )

    col1, col2, col3, col4 = st.columns(4)

    with col1:

        st.metric(
            "ROC-AUC",
            _fmt(
                roc.get("AUC"),
                4,
            ),
        )

    with col2:

        sensitivity = roc.get(
            "sensitivity"
        )

        st.metric(
            "Sensitivity",
            f"{float(sensitivity) * 100:.2f}%"
            if sensitivity is not None
            else "N/A",
        )

    with col3:

        specificity = roc.get(
            "specificity"
        )

        st.metric(
            "Specificity",
            f"{float(specificity) * 100:.2f}%"
            if specificity is not None
            else "N/A",
        )

    with col4:

        status = top.get(
            "validation_status"
        )

        st.metric(
            "Validation Status",
            status if status else "N/A",
        )

    # ==========================================================
    # INDEPENDENT VALIDATION
    # ==========================================================

    st.subheader(
        "🧪 Independent Validation Evidence"
    )

    validation_rows = []

    for key, value in validation.items():

        if value is not None:

            validation_rows.append(
                {
                    "Metric": key,
                    "Value": value,
                }
            )

    if validation_rows:

        st.dataframe(
            pd.DataFrame(validation_rows),
            use_container_width=True,
            hide_index=True,
        )

    else:

        st.info(
            "No independent-validation fields "
            "are available for this biomarker."
        )

    # ==========================================================
    # MACHINE LEARNING
    # ==========================================================

    st.subheader(
        "🤖 Machine Learning Evidence"
    )

    col1, col2, col3 = st.columns(3)

    with col1:

        ml_rank = ml.get(
            "ML_rank"
        )

        st.metric(
            "ML Rank",
            f"#{int(ml_rank)}"
            if ml_rank is not None
            else "N/A",
        )

    with col2:

        st.metric(
            "Feature Importance",
            _fmt(
                ml.get("importance"),
                4,
            ),
        )

    with col3:

        st.metric(
            "ML Evidence Score",
            _fmt(
                integrated.get(
                    "score_ML"
                ),
                3,
            ),
        )

    # ==========================================================
    # STABILITY
    # ==========================================================

    st.subheader("🔬 Biomarker Stability")

    col1, col2, col3, col4 = st.columns(4)

    with col1:
        st.metric(
            "Stability Score",
            _fmt(
                stability.get("stability_score"),
                4,
            ),
        )

    with col2:
        stability_rank = stability.get("stability_rank")

        st.metric(
            "Stability Rank",
            f"#{int(stability_rank)}"
            if stability_rank is not None
            else "N/A",
        )

    with col3:
        top10 = stability.get("top10_stability")

        st.metric(
            "Top-10 Stability",
            f"{float(top10) * 100:.0f}%"
            if top10 is not None
            else "N/A",
        )

    with col4:
        top20 = stability.get("top20_stability")

        st.metric(
            "Top-20 Stability",
            f"{float(top20) * 100:.0f}%"
            if top20 is not None
            else "N/A",
        )

    st.markdown("**Stability Evidence Components**")

    stability_items = {
        "Mean Random-Forest Importance":
            stability.get("mean_rf_importance"),

        "SD Random-Forest Importance":
            stability.get("sd_rf_importance"),

        "Mean Permutation Importance":
            stability.get("mean_permutation_importance"),

        "SD Permutation Importance":
            stability.get("sd_permutation_importance"),

        "Mean Random-Forest Rank":
            stability.get("mean_rf_rank"),

        "Mean Permutation Rank":
            stability.get("mean_permutation_rank"),

        "Top-10 Folds":
            stability.get("top10_folds"),

        "Top-20 Folds":
            stability.get("top20_folds"),

        "Normalized Random-Forest":
            stability.get("normalized_rf"),

        "Normalized Permutation":
            stability.get("normalized_permutation"),
    }

    stability_rows = []

    for label, value in stability_items.items():

        if value is not None:
            stability_rows.append(
                {
                    "Metric": label,
                    "Value": value,
                }
            )

    if stability_rows:
        st.dataframe(
            pd.DataFrame(stability_rows),
            use_container_width=True,
            hide_index=True,
        )
    else:
        st.info(
            "No detailed stability evidence is available "
            "for this biomarker."
        )

    # ==========================================================
    # DIFFERENTIAL EXPRESSION
    # ==========================================================

    st.subheader(
        "🧬 Differential Expression"
    )

    col1, col2, col3, col4 = st.columns(4)

    with col1:

        direction = de.get(
            "direction"
        )

        st.metric(
            "Direction",
            direction
            if direction
            else "N/A",
        )

    with col2:

        st.metric(
            "Base Mean",
            _fmt(
                de.get(
                    "baseMean"
                ),
                2,
            ),
        )

    with col3:

        st.metric(
            "log₂ Fold Change",
            _fmt(
                de.get(
                    "log2FoldChange"
                ),
                3,
            ),
        )

    with col4:

        st.metric(
            "Adjusted p-value",
            _fmt(
                de.get(
                    "padj"
                ),
                6,
            ),
        )

    # ==========================================================
    # INTEGRATED RANKING
    # ==========================================================

    st.subheader(
        "🏆 Official Integrated Ranking"
    )

    ranking_rows = [
        {
            "Component": "Integrated Score",
            "Value": integrated.get(
                "integrated_score"
            ),
        },
        {
            "Component": "Integrated Rank",
            "Value": integrated.get(
                "integrated_rank"
            ),
        },
        {
            "Component": "ROC/AUC",
            "Value": integrated.get(
                "score_AUC"
            ),
        },
        {
            "Component": "Sensitivity",
            "Value": integrated.get(
                "score_sensitivity"
            ),
        },
        {
            "Component": "Specificity",
            "Value": integrated.get(
                "score_specificity"
            ),
        },
        {
            "Component": "Stability",
            "Value": integrated.get(
                "score_stability"
            ),
        },
        {
            "Component": "Machine Learning",
            "Value": integrated.get(
                "score_ML"
            ),
        },
        {
            "Component": "Differential Expression",
            "Value": integrated.get(
                "score_DE"
            ),
        },
    ]

    ranking_rows = [
        row
        for row in ranking_rows
        if row["Value"] is not None
    ]

    if ranking_rows:

        st.dataframe(
            pd.DataFrame(
                ranking_rows
            ),
            use_container_width=True,
            hide_index=True,
        )

    st.caption(
        "These values are retrieved from the existing V1-derived "
        "evidence. V2 does not recalculate or modify the official "
        "integrated ranking."
    )
