import streamlit as st

from core.evidence_engine import get_biomarker_evidence


def _safe_float(value, decimals=3):
    """Safely format numeric values."""
    try:
        if value is None:
            return "N/A"
        return f"{float(value):.{decimals}f}"
    except (TypeError, ValueError):
        return "N/A"


def _safe_int(value):
    """Safely format integer values."""
    try:
        if value is None:
            return "N/A"
        return str(int(value))
    except (TypeError, ValueError):
        return "N/A"


def show_evidence_explorer(data):
    """
    Display evidence-based biomarker profile.

    All values are retrieved from the canonical V1 datasets
    through the V2 evidence engine.
    """

    st.title("🧬 Biomarker Evidence Explorer")

    st.markdown(
        """
        Explore the evidence supporting each biomarker candidate.

        **Important:** All numerical evidence shown here comes from the
        existing V1 pipeline outputs. V2 does not create a competing
        biological score.
        """
    )

    st.divider()

    ranking = data.get("integrated_ranking")
    top15 = data.get("top15")

    # --------------------------------------------------
    # Determine available genes
    # --------------------------------------------------

    genes = []

    if ranking is not None and not ranking.empty:
        if "gene_name" in ranking.columns:
            genes = (
                ranking["gene_name"]
                .dropna()
                .astype(str)
                .unique()
                .tolist()
            )

    elif top15 is not None and not top15.empty:
        if "gene_name" in top15.columns:
            genes = (
                top15["gene_name"]
                .dropna()
                .astype(str)
                .unique()
                .tolist()
            )

    if not genes:
        st.error("No biomarker genes are available.")
        return

    # --------------------------------------------------
    # Gene selector
    # --------------------------------------------------

    selected_gene = st.selectbox(
        "Select biomarker",
        genes,
        index=0,
    )

    # --------------------------------------------------
    # Retrieve grounded evidence
    # --------------------------------------------------

    evidence = get_biomarker_evidence(
        data,
        selected_gene,
    )

    if not evidence:
        st.warning(
            f"No evidence could be retrieved for {selected_gene}."
        )
        return

    # --------------------------------------------------
    # Header
    # --------------------------------------------------

    st.header(f"🔬 {selected_gene}")

    st.caption(
        "Evidence retrieved from canonical V1 pipeline outputs."
    )

    # --------------------------------------------------
    # Integrated ranking
    # --------------------------------------------------

    integrated = evidence.get(
        "integrated_ranking",
        {},
    )

    if integrated:
        st.subheader("🏆 Integrated Evidence")

        col1, col2, col3 = st.columns(3)

        with col1:
            st.metric(
                "Official Integrated Score",
                _safe_float(
                    integrated.get("integrated_score")
                ),
            )

        with col2:
            st.metric(
                "Integrated Rank",
                _safe_int(
                    integrated.get("integrated_rank")
                ),
            )

        with col3:
            st.metric(
                "AUC",
                _safe_float(
                    integrated.get("score_AUC")
                ),
            )

        st.info(
            "The Integrated Score and Rank shown above are "
            "the official values generated by the V1 pipeline."
        )

    st.divider()

    # --------------------------------------------------
    # ROC / Validation
    # --------------------------------------------------

    roc = evidence.get(
        "roc_validation",
        {},
    )

    if roc:
        st.subheader("📈 ROC / Diagnostic Performance")

        col1, col2, col3 = st.columns(3)

        with col1:
            st.metric(
                "ROC-AUC",
                _safe_float(
                    roc.get("AUC")
                ),
            )

        with col2:
            st.metric(
                "Sensitivity",
                _safe_float(
                    roc.get("sensitivity")
                ),
            )

        with col3:
            st.metric(
                "Specificity",
                _safe_float(
                    roc.get("specificity")
                ),
            )

    # --------------------------------------------------
    # Independent validation
    # --------------------------------------------------

    validation = evidence.get(
        "independent_validation",
        {},
    )

    if validation:
        st.subheader("🧪 Independent Validation")

        col1, col2 = st.columns(2)

        with col1:
            st.metric(
                "Direction",
                str(
                    validation.get(
                        "direction",
                        "N/A",
                    )
                ),
            )

        with col2:
            status = validation.get(
                "validation_status"
            )

            if status is not None:
                st.metric(
                    "Validation Status",
                    str(status),
                )

    # --------------------------------------------------
    # Machine learning
    # --------------------------------------------------

    ml = evidence.get(
        "machine_learning",
        {},
    )

    if ml:
        st.subheader("🤖 Machine Learning Evidence")

        col1, col2 = st.columns(2)

        with col1:
            st.metric(
                "Feature Importance",
                _safe_float(
                    ml.get("importance")
                ),
            )

        with col2:
            st.metric(
                "ML Rank",
                _safe_int(
                    ml.get("ML_rank")
                ),
            )
    # --------------------------------------------------
    # Stability
    # --------------------------------------------------

    stability = evidence.get(
        "stability",
        {},
    )

    if stability:
        st.subheader("🔬 Biomarker Stability")

        col1, col2, col3, col4 = st.columns(4)

        with col1:
            st.metric(
                "Stability Score",
                _safe_float(
                    stability.get("stability_score"),
                    4,
                ),
            )

        with col2:
            st.metric(
                "Stability Rank",
                _safe_int(
                    stability.get("stability_rank")
                ),
            )

        with col3:
            top10 = stability.get("top10_stability")

            st.metric(
                "Top-10 Stability",
                f"{float(top10) * 100:.0f}%"
                if top10 is not None
                else "N/A",
            )

        with col4:
            top20 = stability.get("top20_stability")

            st.metric(
                "Top-20 Stability",
                f"{float(top20) * 100:.0f}%"
                if top20 is not None
                else "N/A",
            )
    # --------------------------------------------------
    # Differential expression
    # --------------------------------------------------

    de = evidence.get(
        "differential_expression",
        {},
    )

    if de:
        st.subheader("🧬 Differential Expression")

        col1, col2, col3 = st.columns(3)

        with col1:
            st.metric(
                "log₂ Fold Change",
                _safe_float(
                    de.get("log2FoldChange")
                ),
            )

        with col2:
            st.metric(
                "Adjusted p-value",
                _safe_float(
                    de.get("padj"),
                    4,
                ),
            )

        with col3:
            st.metric(
                "Base Mean",
                _safe_float(
                    de.get("baseMean"),
                    1,
                ),
            )

    # --------------------------------------------------
    # Evidence availability
    # --------------------------------------------------

    st.divider()

    st.subheader("🔎 Evidence Availability")

    available = []

    for key, label in [
        ("integrated_ranking", "Integrated Ranking"),
        ("top15", "Top Biomarkers"),
        ("roc_validation", "ROC / Validation"),
        ("independent_validation", "Independent Validation"),
        ("machine_learning", "Machine Learning"),
        ("stability", "Stability"),
        ("differential_expression", "Differential Expression"),
    ]:
        if evidence.get(key):
            available.append(label)

    if available:
        st.success(
            f"Evidence available across {len(available)} "
            f"analysis layers."
        )

        st.write(
            " • ".join(available)
        )

    else:
        st.warning(
            "No supporting evidence layers were found."
        )

    st.caption(
        "Data provenance: canonical V1 analysis outputs • "
        "V2 presentation and interpretation layer"
    )
