import streamlit as st
import pandas as pd
import plotly.express as px


def show_integrated_ranking(data):

    st.title("🏆 Integrated Biomarker Ranking")

    st.markdown(
        """
        Explore the final evidence-based ranking of LUAD biomarker
        candidates generated by the V1 analysis pipeline.
        
        The integrated score shown here is the existing pipeline
        output and is not recalculated by V2.
        """
    )

    st.divider()

    ranking = data.get("integrated_ranking")

    if ranking is None or ranking.empty:

        st.error(
            "Integrated biomarker ranking data could not be loaded."
        )

        return

    # ==========================================================
    # SUMMARY
    # ==========================================================

    st.subheader("📊 Ranking Summary")

    col1, col2, col3, col4 = st.columns(4)

    with col1:
        st.metric(
            "Candidate Biomarkers",
            len(ranking)
        )

    with col2:
        if "integrated_score" in ranking.columns:
            best_score = ranking["integrated_score"].max()
            st.metric(
                "Highest Integrated Score",
                f"{best_score:.3f}"
            )
        else:
            st.metric(
                "Highest Integrated Score",
                "N/A"
            )

    with col3:
        if "integrated_rank" in ranking.columns:
            best_rank = ranking["integrated_rank"].min()
            st.metric(
                "Best Rank",
                int(best_rank)
            )
        else:
            st.metric(
                "Best Rank",
                "N/A"
            )

    with col4:
        if "AUC" in ranking.columns:
            best_auc = ranking["AUC"].max()
            st.metric(
                "Best ROC-AUC",
                f"{best_auc:.3f}"
            )
        else:
            st.metric(
                "Best ROC-AUC",
                "N/A"
            )

    st.divider()

    # ==========================================================
    # TOP BIOMARKERS
    # ==========================================================

    st.subheader("🥇 Top Ranked Biomarkers")

    display_df = ranking.copy()

    if "integrated_rank" in display_df.columns:

        display_df = display_df.sort_values(
            "integrated_rank",
            ascending=True
        )

    top_n = st.slider(
        "Number of biomarkers to display",
        min_value=5,
        max_value=min(40, len(display_df)),
        value=min(15, len(display_df)),
        step=5,
    )

    top_df = display_df.head(top_n)

    # ==========================================================
    # TABLE
    # ==========================================================

    columns = [
        "integrated_rank",
        "gene_name",
        "integrated_score",
        "score_AUC",
        "score_sensitivity",
        "score_specificity",
        "score_stability",
        "score_ML",
        "score_DE",
        "AUC",
    ]

    columns = [
        column
        for column in columns
        if column in top_df.columns
    ]

    st.dataframe(
        top_df[columns],
        use_container_width=True,
        hide_index=True,
    )

    st.divider()

    # ==========================================================
    # SCORE VISUALIZATION
    # ==========================================================

    st.subheader("📈 Integrated Score Distribution")

    if "integrated_score" in display_df.columns:

        fig = px.bar(
            top_df.sort_values(
                "integrated_score",
                ascending=True
            ),
            x="integrated_score",
            y="gene_name",
            orientation="h",
            title="Integrated Evidence Score",
            hover_data=[
                column
                for column in [
                    "integrated_rank",
                    "AUC",
                    "score_AUC",
                    "score_sensitivity",
                    "score_specificity",
                    "score_stability",
                    "score_ML",
                    "score_DE",
                ]
                if column in top_df.columns
            ],
        )

        fig.update_layout(
            height=max(500, top_n * 35),
            yaxis_title="Biomarker",
            xaxis_title="Integrated Score",
        )

        st.plotly_chart(
            fig,
            use_container_width=True
        )

    # ==========================================================
    # INDIVIDUAL BIOMARKER
    # ==========================================================

    st.divider()

    st.subheader("🔎 Explore Individual Biomarker")

    if "gene_name" in display_df.columns:

        genes = display_df["gene_name"].dropna().tolist()

        selected_gene = st.selectbox(
            "Select biomarker",
            genes
        )

        selected = display_df[
            display_df["gene_name"] == selected_gene
        ].iloc[0]

        st.markdown(
            f"### 🧬 {selected_gene}"
        )

        col1, col2, col3 = st.columns(3)

        with col1:

            if "integrated_rank" in selected:
                st.metric(
                    "Integrated Rank",
                    int(selected["integrated_rank"])
                )

        with col2:

            if "integrated_score" in selected:
                st.metric(
                    "Integrated Score",
                    f"{selected['integrated_score']:.3f}"
                )

        with col3:

            if "AUC" in selected:
                st.metric(
                    "ROC-AUC",
                    f"{selected['AUC']:.3f}"
                )

        # ======================================================
        # SCORE COMPONENTS
        # ======================================================

        score_columns = [
            "score_AUC",
            "score_sensitivity",
            "score_specificity",
            "score_stability",
            "score_ML",
            "score_DE",
        ]

        available_scores = [
            column
            for column in score_columns
            if column in selected.index
        ]

        if available_scores:

            st.subheader("🧩 Evidence Score Components")

            score_data = pd.DataFrame(
                {
                    "Evidence Component": [
                        column.replace("score_", "").replace(
                            "_", " "
                        ).title()
                        for column in available_scores
                    ],
                    "Score": [
                        selected[column]
                        for column in available_scores
                    ],
                }
            )

            fig = px.bar(
                score_data,
                x="Evidence Component",
                y="Score",
                title=f"Evidence Components — {selected_gene}",
            )

            fig.update_layout(
                height=400,
                xaxis_title="",
                yaxis_title="Score",
            )

            st.plotly_chart(
                fig,
                use_container_width=True
            )

            st.dataframe(
                score_data,
                use_container_width=True,
                hide_index=True,
            )

    # ==========================================================
    # EXPLANATION
    # ==========================================================

    st.divider()

    st.subheader("🧠 How the Integrated Ranking Works")

    st.info(
        """
        The integrated ranking shown on this page comes directly
        from the V1 biomarker-ranking output.

        It combines six existing evidence components:

        • ROC/AUC performance
        • Sensitivity
        • Specificity
        • Biomarker stability
        • Machine-learning evidence
        • Differential-expression evidence

        V2 does not modify or recalculate the official ranking.
        It provides a transparent interface for exploring the
        existing evidence.
        """
    )

    # ==========================================================
    # PROVENANCE
    # ==========================================================

    st.divider()

    st.caption(
        "Source: results/final/"
        "LUAD_integrated_biomarker_ranking.csv"
    )
