import streamlit as st
import pandas as pd
import plotly.express as px


def show_roc_validation(roc_results, validation_stats, validation_ranking):

    st.title("📈 ROC / Independent Validation")

    st.markdown(
        """
        ### Independent Validation of LUAD Biomarker Candidates

        This page presents ROC/AUC performance and independent-cohort
        validation results generated by the V1 analysis pipeline.

        **V2 does not recalculate the validation statistics.**
        """

    )

    if roc_results is None or roc_results.empty:
        st.error(
            "ROC/AUC results could not be loaded."
        )
        return

    roc = roc_results.copy()

    # ==================================================
    # NUMERIC CONVERSION
    # ==================================================

    numeric_columns = [
        "AUC",
        "CI_lower",
        "CI_upper",
        "sensitivity",
        "specificity",
    ]

    for column in numeric_columns:

        if column in roc.columns:

            roc[column] = pd.to_numeric(
                roc[column],
                errors="coerce"
            )

    # ==================================================
    # SUMMARY
    # ==================================================

    st.subheader("📊 Validation Summary")

    n_genes = len(roc)

    mean_auc = (
        roc["AUC"].mean()
        if "AUC" in roc.columns
        else 0
    )

    best_auc = (
        roc["AUC"].max()
        if "AUC" in roc.columns
        else 0
    )

    best_gene = "N/A"

    if (
        "AUC" in roc.columns
        and "gene_name" in roc.columns
        and not roc.empty
    ):

        best_row = roc.loc[
            roc["AUC"].idxmax()
        ]

        best_gene = best_row["gene_name"]

    col1, col2, col3, col4 = st.columns(4)

    with col1:
        st.metric(
            "Validated Genes",
            f"{n_genes:,}"
        )

    with col2:
        st.metric(
            "Mean ROC-AUC",
            f"{mean_auc:.3f}"
        )

    with col3:
        st.metric(
            "Best ROC-AUC",
            f"{best_auc:.3f}"
        )

    with col4:
        st.metric(
            "Best Biomarker",
            str(best_gene)
        )

    st.divider()

    # ==================================================
    # GENE SEARCH
    # ==================================================

    st.subheader("🔎 Explore Validation Results")

    search_gene = st.text_input(
        "Search biomarker",
        placeholder="e.g. EGFR, TP53, KRAS"
    )

    filtered = roc.copy()

    if search_gene.strip() and "gene_name" in filtered.columns:

        filtered = filtered[
            filtered["gene_name"]
            .astype(str)
            .str.contains(
                search_gene.strip(),
                case=False,
                na=False
            )
        ]

    st.write(
        f"Showing **{len(filtered):,}** biomarkers"
    )

    # ==================================================
    # AUC RANKING
    # ==================================================

    if "AUC" in filtered.columns:

        st.subheader("🏆 ROC-AUC Ranking")

        auc_df = (
            filtered
            .sort_values(
                "AUC",
                ascending=True
            )
        )

        fig = px.bar(
            auc_df,
            x="AUC",
            y="gene_name",
            orientation="h",
            title="Diagnostic Performance of Validated Biomarkers",
            hover_data=[
                c
                for c in [
                    "AUC",
                    "CI_lower",
                    "CI_upper",
                    "sensitivity",
                    "specificity",
                ]
                if c in auc_df.columns
            ],
        )

        fig.update_layout(
            height=max(
                500,
                len(auc_df) * 25
            ),
            xaxis_title="ROC-AUC",
            yaxis_title="Gene",
        )

        st.plotly_chart(
            fig,
            use_container_width=True
        )

    # ==================================================
    # SELECT BIOMARKER
    # ==================================================

    if (
        "gene_name" in filtered.columns
        and not filtered.empty
    ):

        st.subheader("🔬 Biomarker Validation Detail")

        selected_gene = st.selectbox(
            "Select a biomarker",
            filtered["gene_name"]
            .dropna()
            .astype(str)
            .tolist()
        )

        selected = filtered[
            filtered["gene_name"].astype(str)
            == selected_gene
        ].iloc[0]

        col1, col2, col3, col4 = st.columns(4)

        with col1:

            if "AUC" in selected.index:

                st.metric(
                    "ROC-AUC",
                    f"{selected['AUC']:.3f}"
                )

        with col2:

            if "sensitivity" in selected.index:

                st.metric(
                    "Sensitivity",
                    f"{selected['sensitivity'] * 100:.1f}%"
                )

        with col3:

            if "specificity" in selected.index:

                st.metric(
                    "Specificity",
                    f"{selected['specificity'] * 100:.1f}%"
                )

        with col4:

            if "CI_lower" in selected.index:

                st.metric(
                    "95% CI",
                    f"{selected['CI_lower']:.3f}–"
                    f"{selected['CI_upper']:.3f}"
                )

    st.divider()

    # ==================================================
    # INDEPENDENT VALIDATION STATISTICS
    # ==================================================

    st.subheader("🧪 Independent Cohort Validation")

    if (
        validation_stats is not None
        and not validation_stats.empty
    ):

        stats = validation_stats.copy()

        st.caption(
            "Independent validation statistics from the V1 pipeline."
        )

        st.dataframe(
            stats,
            use_container_width=True,
            hide_index=True
        )

    else:

        st.info(
            "Independent validation statistics are not available."
        )

    # ==================================================
    # VALIDATION RANKING
    # ==================================================

    if (
        validation_ranking is not None
        and not validation_ranking.empty
    ):

        st.subheader("🏆 Validation Ranking")

        ranking = validation_ranking.copy()

        st.dataframe(
            ranking,
            use_container_width=True,
            hide_index=True
        )

    # ==================================================
    # DOWNLOAD
    # ==================================================

    st.subheader("📥 Download Validation Results")

    csv = filtered.to_csv(
        index=False
    ).encode("utf-8")

    st.download_button(
        label="📥 Download ROC/AUC Results",
        data=csv,
        file_name="LUAD_ROC_AUC_validation_results.csv",
        mime="text/csv",
    )
